INFO 2024-05-11 16:04:36,685 autoreload 69381 140469481382976 Watching for file changes with StatReloader
INFO 2024-05-11 16:08:08,760 autoreload 71710 139718018225216 Watching for file changes with StatReloader
WARNING 2024-05-11 16:08:19,687 log 71710 139717961418304 Unauthorized: /api/goods/
WARNING 2024-05-11 16:08:19,688 basehttp 71710 139717961418304 "GET /api/goods/ HTTP/1.1" 401 43
INFO 2024-05-11 16:09:11,060 autoreload 72411 140164479288384 Watching for file changes with StatReloader
INFO 2024-05-11 16:09:12,255 basehttp 72411 140164422481472 "GET /api/goods/ HTTP/1.1" 200 52
INFO 2024-05-11 16:10:12,633 basehttp 72411 140164422481472 "POST /api/goods/ HTTP/1.1" 201 82
INFO 2024-05-11 16:10:16,669 basehttp 72411 140164422481472 "GET /api/goods/ HTTP/1.1" 200 134
ERROR 2024-05-11 16:11:32,604 log 72411 140164422481472 Internal Server Error: /api/goods/1
Traceback (most recent call last):
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/django/utils/deprecation.py", line 136, in __call__
    response = self.process_response(request, response)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/django/middleware/common.py", line 108, in process_response
    return self.response_redirect_class(self.get_full_path_with_slash(request))
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/django/middleware/common.py", line 87, in get_full_path_with_slash
    raise RuntimeError(
RuntimeError: You called this URL via PATCH, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining PATCH data. Change your form to point to 127.0.0.1:8000/api/goods/1/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
ERROR 2024-05-11 16:11:32,604 basehttp 72411 140164422481472 "PATCH /api/goods/1 HTTP/1.1" 500 73440
INFO 2024-05-11 16:12:09,393 basehttp 72411 140164422481472 "PATCH /api/goods/1/ HTTP/1.1" 200 82
INFO 2024-05-11 16:12:13,345 basehttp 72411 140164422481472 "GET /api/goods/ HTTP/1.1" 200 134
WARNING 2024-05-11 16:14:32,499 log 72411 140164422481472 Bad Request: /api/goods/
WARNING 2024-05-11 16:14:32,500 basehttp 72411 140164422481472 "POST /api/goods/ HTTP/1.1" 400 56
WARNING 2024-05-11 16:14:42,206 log 72411 140164422481472 Bad Request: /api/goods/
WARNING 2024-05-11 16:14:42,206 basehttp 72411 140164422481472 "POST /api/goods/ HTTP/1.1" 400 41
INFO 2024-05-11 20:38:17,953 autoreload 232991 140590212011072 Watching for file changes with StatReloader
INFO 2024-05-11 20:39:11,753 autoreload 233743 140310919541824 Watching for file changes with StatReloader
INFO 2024-05-11 20:39:46,595 basehttp 233743 140310856332864 "GET /api/goods/ HTTP/1.1" 200 52
WARNING 2024-05-11 20:41:11,827 log 233743 140310856332864 Bad Request: /api/goods/
WARNING 2024-05-11 20:41:11,827 basehttp 233743 140310856332864 "POST /api/goods/ HTTP/1.1" 400 157
INFO 2024-05-11 20:41:48,779 autoreload 233743 140310919541824 /home/mk/python/BUYproject/goods/views.py changed, reloading.
INFO 2024-05-11 20:41:48,965 autoreload 235357 140127248970816 Watching for file changes with StatReloader
INFO 2024-05-11 20:41:52,174 autoreload 235413 140669451547712 Watching for file changes with StatReloader
WARNING 2024-05-11 20:41:55,068 log 235413 140669388322368 Bad Request: /api/goods/
WARNING 2024-05-11 20:41:55,069 basehttp 235413 140669388322368 "POST /api/goods/ HTTP/1.1" 400 38
WARNING 2024-05-11 20:42:46,173 log 235413 140669388322368 Bad Request: /api/goods/
WARNING 2024-05-11 20:42:46,174 basehttp 235413 140669388322368 "POST /api/goods/ HTTP/1.1" 400 38
INFO 2024-05-11 20:43:00,721 autoreload 235413 140669451547712 /home/mk/python/BUYproject/goods/serializers.py changed, reloading.
INFO 2024-05-11 20:43:00,904 autoreload 235937 140529127945280 Watching for file changes with StatReloader
INFO 2024-05-11 20:43:04,055 autoreload 235937 140529127945280 /home/mk/python/BUYproject/goods/serializers.py changed, reloading.
INFO 2024-05-11 20:43:04,228 autoreload 235984 139867539809344 Watching for file changes with StatReloader
INFO 2024-05-11 20:43:07,399 autoreload 236014 140201956205632 Watching for file changes with StatReloader
INFO 2024-05-11 20:43:08,960 basehttp 236014 140201825400384 "POST /api/goods/ HTTP/1.1" 201 127
INFO 2024-05-11 20:43:55,725 basehttp 236014 140201825400384 "POST /api/goods/ HTTP/1.1" 201 113
WARNING 2024-05-11 20:48:52,548 log 236014 140201825400384 Bad Request: /api/price/
WARNING 2024-05-11 20:48:52,548 basehttp 236014 140201825400384 "POST /api/price/ HTTP/1.1" 400 120
WARNING 2024-05-11 20:49:14,036 log 236014 140201825400384 Bad Request: /api/price/
WARNING 2024-05-11 20:49:14,036 basehttp 236014 140201825400384 "POST /api/price/ HTTP/1.1" 400 120
INFO 2024-05-11 20:49:29,746 autoreload 236014 140201956205632 /home/mk/python/BUYproject/goods/urls.py changed, reloading.
INFO 2024-05-11 20:49:29,933 autoreload 239495 140448353842240 Watching for file changes with StatReloader
INFO 2024-05-11 20:49:32,586 autoreload 239547 140496749392960 Watching for file changes with StatReloader
ERROR 2024-05-11 20:49:34,527 log 239547 140496686282304 Internal Server Error: /api/price/
Traceback (most recent call last):
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/MySQLdb/connections.py", line 259, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.OperationalError: (1048, "Column 'product_id' cannot be null")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/mixins.py", line 19, in create
    self.perform_create(serializer)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/mixins.py", line 24, in perform_create
    serializer.save()
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/serializers.py", line 212, in save
    self.instance = self.create(validated_data)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/serializers.py", line 962, in create
    instance = ModelClass._default_manager.create(**validated_data)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/django/db/models/query.py", line 658, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/django/db/models/base.py", line 814, in save
    self.save_base(
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/django/db/models/base.py", line 877, in save_base
    updated = self._save_table(
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/django/db/models/base.py", line 1020, in _save_table
    results = self._do_insert(
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/django/db/models/base.py", line 1061, in _do_insert
    return manager._insert(
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/django/db/models/query.py", line 1805, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1822, in execute_sql
    cursor.execute(sql, params)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/django/db/backends/mysql/base.py", line 80, in execute
    raise IntegrityError(*tuple(e.args))
django.db.utils.IntegrityError: (1048, "Column 'product_id' cannot be null")
ERROR 2024-05-11 20:49:34,528 basehttp 239547 140496686282304 "POST /api/price/ HTTP/1.1" 500 199035
ERROR 2024-05-11 20:50:02,008 log 239547 140496686282304 Internal Server Error: /api/price/
Traceback (most recent call last):
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/MySQLdb/connections.py", line 259, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.OperationalError: (1048, "Column 'product_id' cannot be null")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/mixins.py", line 19, in create
    self.perform_create(serializer)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/mixins.py", line 24, in perform_create
    serializer.save()
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/serializers.py", line 212, in save
    self.instance = self.create(validated_data)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/serializers.py", line 962, in create
    instance = ModelClass._default_manager.create(**validated_data)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/django/db/models/query.py", line 658, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/django/db/models/base.py", line 814, in save
    self.save_base(
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/django/db/models/base.py", line 877, in save_base
    updated = self._save_table(
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/django/db/models/base.py", line 1020, in _save_table
    results = self._do_insert(
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/django/db/models/base.py", line 1061, in _do_insert
    return manager._insert(
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/django/db/models/query.py", line 1805, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1822, in execute_sql
    cursor.execute(sql, params)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/django/db/backends/mysql/base.py", line 80, in execute
    raise IntegrityError(*tuple(e.args))
django.db.utils.IntegrityError: (1048, "Column 'product_id' cannot be null")
ERROR 2024-05-11 20:50:02,008 basehttp 239547 140496686282304 "POST /api/price/ HTTP/1.1" 500 199035
INFO 2024-05-11 20:52:37,341 autoreload 241184 140701071627328 Watching for file changes with StatReloader
INFO 2024-05-11 20:52:38,726 basehttp 241184 140701008393792 "GET /api/goods/ HTTP/1.1" 200 293
INFO 2024-05-11 20:59:57,529 autoreload 245606 139959649059904 Watching for file changes with StatReloader
ERROR 2024-05-11 21:00:06,481 log 245606 139959585732160 Internal Server Error: /api/goods/
Traceback (most recent call last):
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/mixins.py", line 19, in create
    self.perform_create(serializer)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/mixins.py", line 24, in perform_create
    serializer.save()
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/serializers.py", line 212, in save
    self.instance = self.create(validated_data)
  File "/home/mk/python/BUYproject/goods/serializers.py", line 18, in create
    price = validated_data.pop('price')
KeyError: 'price'
ERROR 2024-05-11 21:00:06,481 basehttp 245606 139959585732160 "POST /api/goods/ HTTP/1.1" 500 112117
INFO 2024-05-11 21:01:05,579 autoreload 246341 139810329982016 Watching for file changes with StatReloader
ERROR 2024-05-11 21:01:07,408 log 246341 139810266674752 Internal Server Error: /api/goods/
Traceback (most recent call last):
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/mixins.py", line 19, in create
    self.perform_create(serializer)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/mixins.py", line 24, in perform_create
    serializer.save()
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/serializers.py", line 212, in save
    self.instance = self.create(validated_data)
  File "/home/mk/python/BUYproject/goods/serializers.py", line 22, in create
    PriceModel.objects.create(product=goods, price=price.get('price'), start_time=start_time, end_time=end_time)
AttributeError: 'decimal.Decimal' object has no attribute 'get'
ERROR 2024-05-11 21:01:07,408 basehttp 246341 139810266674752 "POST /api/goods/ HTTP/1.1" 500 113003
INFO 2024-05-11 21:01:21,831 autoreload 246341 139810329982016 /home/mk/python/BUYproject/goods/serializers.py changed, reloading.
INFO 2024-05-11 21:01:22,020 autoreload 246542 140660574872640 Watching for file changes with StatReloader
ERROR 2024-05-11 21:01:23,926 log 246542 140660444493376 Internal Server Error: /api/goods/
Traceback (most recent call last):
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/fields.py", line 446, in get_attribute
    return get_attribute(instance, self.source_attrs)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/fields.py", line 96, in get_attribute
    instance = getattr(instance, attr)
AttributeError: 'GoodsModel' object has no attribute 'price'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/mixins.py", line 20, in create
    headers = self.get_success_headers(serializer.data)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/serializers.py", line 555, in data
    ret = super().data
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/serializers.py", line 509, in to_representation
    attribute = field.get_attribute(instance)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/fields.py", line 479, in get_attribute
    raise type(exc)(msg)
AttributeError: Got AttributeError when attempting to get a value for field `price` on serializer `GoodsModelSerializer`.
The serializer field might be named incorrectly and not match any attribute or key on the `GoodsModel` instance.
Original exception text was: 'GoodsModel' object has no attribute 'price'.
ERROR 2024-05-11 21:01:23,927 basehttp 246542 140660444493376 "POST /api/goods/ HTTP/1.1" 500 127163
INFO 2024-05-11 21:08:47,498 autoreload 251041 140339200681024 Watching for file changes with StatReloader
ERROR 2024-05-11 21:08:49,029 log 251041 140339063027264 Internal Server Error: /api/goods/
Traceback (most recent call last):
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/mixins.py", line 18, in create
    serializer.is_valid(raise_exception=True)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/serializers.py", line 227, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/serializers.py", line 426, in run_validation
    value = self.to_internal_value(data)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/serializers.py", line 479, in to_internal_value
    for field in fields:
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/serializers.py", line 362, in _writable_fields
    for field in self.fields.values():
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/serializers.py", line 356, in fields
    for key, value in self.get_fields().items():
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/serializers.py", line 1052, in get_fields
    field_names = self.get_field_names(declared_fields, info)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/serializers.py", line 1124, in get_field_names
    assert not (fields is None and exclude is None), (
AssertionError: ("Creating a ModelSerializer without either the 'fields' attribute or the 'exclude' attribute has been deprecated since 3.3.0, and is now disallowed. Add an explicit fields = '__all__' to the GoodsModelSerializer serializer.",)
ERROR 2024-05-11 21:08:49,030 basehttp 251041 140339063027264 "POST /api/goods/ HTTP/1.1" 500 137198
INFO 2024-05-11 21:09:11,920 autoreload 251351 140350975759424 Watching for file changes with StatReloader
ERROR 2024-05-11 21:09:13,167 log 251351 140350912460352 Internal Server Error: /api/goods/
Traceback (most recent call last):
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/fields.py", line 446, in get_attribute
    return get_attribute(instance, self.source_attrs)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/fields.py", line 96, in get_attribute
    instance = getattr(instance, attr)
AttributeError: 'GoodsModel' object has no attribute 'price'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/mixins.py", line 20, in create
    headers = self.get_success_headers(serializer.data)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/serializers.py", line 555, in data
    ret = super().data
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/serializers.py", line 509, in to_representation
    attribute = field.get_attribute(instance)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/fields.py", line 479, in get_attribute
    raise type(exc)(msg)
AttributeError: Got AttributeError when attempting to get a value for field `price` on serializer `GoodsModelSerializer`.
The serializer field might be named incorrectly and not match any attribute or key on the `GoodsModel` instance.
Original exception text was: 'GoodsModel' object has no attribute 'price'.
ERROR 2024-05-11 21:09:13,168 basehttp 251351 140350912460352 "POST /api/goods/ HTTP/1.1" 500 127453
INFO 2024-05-11 21:10:11,434 autoreload 251351 140350975759424 /home/mk/python/BUYproject/goods/serializers.py changed, reloading.
INFO 2024-05-11 21:10:11,622 autoreload 251976 140362717594688 Watching for file changes with StatReloader
INFO 2024-05-11 21:12:52,861 autoreload 253613 140137120224320 Watching for file changes with StatReloader
ERROR 2024-05-11 21:12:54,393 log 253613 140136989587008 Internal Server Error: /api/goods/
Traceback (most recent call last):
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/mixins.py", line 19, in create
    self.perform_create(serializer)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/mixins.py", line 24, in perform_create
    serializer.save()
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/serializers.py", line 212, in save
    self.instance = self.create(validated_data)
  File "/home/mk/python/BUYproject/goods/serializers.py", line 18, in create
    price_data = validated_data.pop('price')
KeyError: 'price'
ERROR 2024-05-11 21:12:54,394 basehttp 253613 140136989587008 "POST /api/goods/ HTTP/1.1" 500 111277
INFO 2024-05-11 21:17:24,264 autoreload 256373 140234624640064 Watching for file changes with StatReloader
INFO 2024-05-11 21:17:27,274 basehttp 256373 140234561418816 "GET /api/goods/ HTTP/1.1" 200 417
INFO 2024-05-11 21:18:25,765 autoreload 256373 140234624640064 /home/mk/python/BUYproject/goods/views.py changed, reloading.
INFO 2024-05-11 21:18:25,948 autoreload 257023 140321158370368 Watching for file changes with StatReloader
INFO 2024-05-11 21:18:27,081 autoreload 257023 140321158370368 /home/mk/python/BUYproject/goods/views.py changed, reloading.
INFO 2024-05-11 21:18:27,261 autoreload 257056 140177978205248 Watching for file changes with StatReloader
INFO 2024-05-11 21:19:26,522 autoreload 257673 140357199332416 Watching for file changes with StatReloader
INFO 2024-05-11 21:29:47,214 autoreload 263890 139734553785408 Watching for file changes with StatReloader
INFO 2024-05-11 21:30:00,515 autoreload 264065 139681760109632 Watching for file changes with StatReloader
WARNING 2024-05-11 21:30:12,155 log 264065 139681696839232 Method Not Allowed: /api/goods/
INFO 2024-05-11 21:30:36,796 autoreload 264496 140027154048064 Watching for file changes with StatReloader
WARNING 2024-05-11 21:30:38,123 log 264496 140027090695744 Bad Request: /api/goods/
WARNING 2024-05-11 21:30:38,124 basehttp 264496 140027090695744 "POST /api/goods/ HTTP/1.1" 400 38
WARNING 2024-05-11 21:30:49,101 log 264496 140027090695744 Bad Request: /api/goods/
WARNING 2024-05-11 21:30:49,101 basehttp 264496 140027090695744 "POST /api/goods/ HTTP/1.1" 400 38
INFO 2024-05-11 21:32:23,544 autoreload 264496 140027154048064 /home/mk/python/BUYproject/goods/serializers.py changed, reloading.
INFO 2024-05-11 21:32:23,734 autoreload 265595 140442842997824 Watching for file changes with StatReloader
WARNING 2024-05-11 21:32:25,668 log 265595 140442779776576 Bad Request: /api/goods/
WARNING 2024-05-11 21:32:25,668 basehttp 265595 140442779776576 "POST /api/goods/ HTTP/1.1" 400 38
INFO 2024-05-12 09:56:50,908 autoreload 5171 139776887428160 Watching for file changes with StatReloader
ERROR 2024-05-12 09:57:03,169 log 5171 139776757069376 Internal Server Error: /api/goods/
Traceback (most recent call last):
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/mixins.py", line 18, in create
    serializer.is_valid(raise_exception=True)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/serializers.py", line 227, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/serializers.py", line 426, in run_validation
    value = self.to_internal_value(data)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/serializers.py", line 479, in to_internal_value
    for field in fields:
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/serializers.py", line 362, in _writable_fields
    for field in self.fields.values():
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/serializers.py", line 356, in fields
    for key, value in self.get_fields().items():
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/serializers.py", line 1052, in get_fields
    field_names = self.get_field_names(declared_fields, info)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/serializers.py", line 1148, in get_field_names
    assert field_name in fields, (
AssertionError: The field 'price_ser' was declared on serializer GoodsModelSerializer, but has not been included in the 'fields' option.
ERROR 2024-05-12 09:57:03,169 basehttp 5171 139776757069376 "POST /api/goods/ HTTP/1.1" 500 136647
INFO 2024-05-12 09:57:17,215 autoreload 5171 139776887428160 /home/mk/python/BUYproject/goods/serializers.py changed, reloading.
INFO 2024-05-12 09:57:17,395 autoreload 5474 140588687672384 Watching for file changes with StatReloader
ERROR 2024-05-12 09:57:19,671 log 5474 140588624377408 Internal Server Error: /api/goods/
Traceback (most recent call last):
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/mixins.py", line 19, in create
    self.perform_create(serializer)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/mixins.py", line 24, in perform_create
    serializer.save()
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/serializers.py", line 212, in save
    self.instance = self.create(validated_data)
  File "/home/mk/python/BUYproject/goods/serializers.py", line 32, in create
    PriceModel.objects.create(product=product, start_time=start_time, end_time=end_time, **price_data)
TypeError: django.db.models.query.QuerySet.create() argument after ** must be a mapping, not decimal.Decimal
ERROR 2024-05-12 09:57:19,671 basehttp 5474 140588624377408 "POST /api/goods/ HTTP/1.1" 500 113223
INFO 2024-05-12 09:57:49,748 autoreload 5474 140588687672384 /home/mk/python/BUYproject/goods/serializers.py changed, reloading.
INFO 2024-05-12 09:57:49,930 autoreload 5837 139966814618688 Watching for file changes with StatReloader
INFO 2024-05-12 09:58:08,800 autoreload 6068 139677647524928 Watching for file changes with StatReloader
INFO 2024-05-12 09:58:10,706 basehttp 6068 139677584324160 "POST /api/goods/ HTTP/1.1" 201 121
INFO 2024-05-12 09:58:43,515 basehttp 6068 139677584324160 "POST /api/goods/ HTTP/1.1" 201 112
INFO 2024-05-12 09:59:14,177 basehttp 6068 139677584324160 "GET /api/goods/ HTTP/1.1" 200 774
INFO 2024-05-12 10:02:57,584 autoreload 6068 139677647524928 /home/mk/python/BUYproject/goods/models.py changed, reloading.
INFO 2024-05-12 10:02:57,766 autoreload 8937 139864685659200 Watching for file changes with StatReloader
INFO 2024-05-12 10:03:42,646 autoreload 9420 140512872383552 Watching for file changes with StatReloader
INFO 2024-05-12 10:03:45,965 basehttp 9420 140512740767296 "POST /api/goods/ HTTP/1.1" 201 112
INFO 2024-05-12 10:07:52,464 autoreload 11784 139736924021824 Watching for file changes with StatReloader
INFO 2024-05-12 10:07:53,816 basehttp 11784 139736860849728 "GET /api/goods/ HTTP/1.1" 200 887
INFO 2024-05-12 10:08:04,728 basehttp 11784 139736860849728 "POST /api/goods/ HTTP/1.1" 201 113
INFO 2024-05-12 10:08:06,707 basehttp 11784 139736860849728 "GET /api/goods/ HTTP/1.1" 200 1001
INFO 2024-05-12 10:12:56,431 autoreload 11784 139736924021824 /home/mk/python/BUYproject/goods/views.py changed, reloading.
INFO 2024-05-12 10:12:56,617 autoreload 14827 140085910434880 Watching for file changes with StatReloader
INFO 2024-05-12 10:12:58,743 autoreload 14827 140085910434880 /home/mk/python/BUYproject/goods/views.py changed, reloading.
INFO 2024-05-12 10:12:58,923 autoreload 14870 140122571420736 Watching for file changes with StatReloader
INFO 2024-05-12 10:13:00,068 autoreload 14870 140122571420736 /home/mk/python/BUYproject/goods/views.py changed, reloading.
INFO 2024-05-12 10:13:00,257 autoreload 14883 139656251180096 Watching for file changes with StatReloader
INFO 2024-05-12 10:13:02,583 basehttp 14883 139656187868736 "GET /api/goods/ HTTP/1.1" 200 951
INFO 2024-05-12 10:18:17,167 autoreload 14883 139656251180096 /home/mk/python/BUYproject/goods/serializers.py changed, reloading.
INFO 2024-05-12 10:18:17,350 autoreload 17894 139868596618304 Watching for file changes with StatReloader
INFO 2024-05-12 10:18:19,504 autoreload 17894 139868596618304 /home/mk/python/BUYproject/goods/serializers.py changed, reloading.
INFO 2024-05-12 10:18:19,683 autoreload 17938 140678282908736 Watching for file changes with StatReloader
INFO 2024-05-12 10:18:23,840 autoreload 17938 140678282908736 /home/mk/python/BUYproject/goods/serializers.py changed, reloading.
INFO 2024-05-12 10:18:24,022 autoreload 17981 140203564860480 Watching for file changes with StatReloader
INFO 2024-05-12 10:18:26,262 basehttp 17981 140203434440256 "GET /api/goods/ HTTP/1.1" 200 951
INFO 2024-05-12 10:18:27,433 basehttp 17981 140203434440256 "GET /api/goods/ HTTP/1.1" 200 951
INFO 2024-05-12 10:18:34,233 autoreload 17981 140203564860480 /home/mk/python/BUYproject/goods/views.py changed, reloading.
INFO 2024-05-12 10:18:34,422 autoreload 18092 140122203305024 Watching for file changes with StatReloader
INFO 2024-05-12 10:18:48,731 basehttp 18092 140122140177984 "GET /api/goods/4/ HTTP/1.1" 200 121
INFO 2024-05-12 10:19:51,018 autoreload 18092 140122203305024 /home/mk/python/BUYproject/goods/serializers.py changed, reloading.
INFO 2024-05-12 10:19:51,206 autoreload 18662 139962008413248 Watching for file changes with StatReloader
INFO 2024-05-12 10:19:52,339 autoreload 18662 139962008413248 /home/mk/python/BUYproject/goods/serializers.py changed, reloading.
INFO 2024-05-12 10:19:52,524 autoreload 18682 140243626468416 Watching for file changes with StatReloader
INFO 2024-05-12 10:19:54,824 basehttp 18682 140243496072768 "GET /api/goods/4/ HTTP/1.1" 200 231
INFO 2024-05-12 10:20:00,761 basehttp 18682 140243496072768 "GET /api/goods HTTP/1.1" 301 0
INFO 2024-05-12 10:20:00,774 basehttp 18682 140243496072768 "GET /api/goods/ HTTP/1.1" 200 1635
INFO 2024-05-12 10:21:20,230 basehttp 18682 140243496072768 "GET /api/goods HTTP/1.1" 301 0
INFO 2024-05-12 10:21:20,240 basehttp 18682 140243496072768 "GET /api/goods/ HTTP/1.1" 200 689
INFO 2024-05-12 10:21:46,311 autoreload 18682 140243626468416 /home/mk/python/BUYproject/goods/views.py changed, reloading.
INFO 2024-05-12 10:21:46,502 autoreload 19640 140132430115904 Watching for file changes with StatReloader
INFO 2024-05-12 10:21:48,056 basehttp 19640 140132299830848 "GET /api/goods HTTP/1.1" 301 0
INFO 2024-05-12 10:21:48,070 basehttp 19640 140132299830848 "GET /api/goods/ HTTP/1.1" 200 739
INFO 2024-05-12 10:22:45,469 basehttp 19640 140132299830848 "POST /api/goods/ HTTP/1.1" 201 247
INFO 2024-05-12 10:22:49,170 basehttp 19640 140132299830848 "GET /api/goods HTTP/1.1" 301 0
INFO 2024-05-12 10:22:49,185 basehttp 19640 140132299830848 "GET /api/goods/ HTTP/1.1" 200 987
INFO 2024-05-12 10:26:26,349 autoreload 19640 140132430115904 /home/mk/python/BUYproject/goods/views.py changed, reloading.
INFO 2024-05-12 10:26:26,535 autoreload 22452 140566550774848 Watching for file changes with StatReloader
INFO 2024-05-12 10:27:48,452 autoreload 23304 139656360236096 Watching for file changes with StatReloader
INFO 2024-05-12 10:27:50,101 basehttp 23304 139656229811776 "GET /api/goods HTTP/1.1" 301 0
ERROR 2024-05-12 10:27:50,121 log 23304 139656229811776 Internal Server Error: /api/goods/
Traceback (most recent call last):
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/mk/python/BUYproject/goods/views.py", line 28, in list
    item['prices'] = [price for price in item['prices'] if price['status']]
  File "/home/mk/python/BUYproject/goods/views.py", line 28, in <listcomp>
    item['prices'] = [price for price in item['prices'] if price['status']]
KeyError: 'status'
ERROR 2024-05-12 10:27:50,122 basehttp 23304 139656229811776 "GET /api/goods/ HTTP/1.1" 500 103347
INFO 2024-05-12 10:30:44,263 autoreload 25116 140217588483136 Watching for file changes with StatReloader
INFO 2024-05-12 10:30:46,017 basehttp 25116 140217458095680 "GET /api/goods HTTP/1.1" 301 0
ERROR 2024-05-12 10:30:46,040 log 25116 140217458095680 Internal Server Error: /api/goods/
Traceback (most recent call last):
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/mixins.py", line 43, in list
    return self.get_paginated_response(serializer.data)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/serializers.py", line 768, in data
    ret = super().data
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/serializers.py", line 686, in to_representation
    return [
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/serializers.py", line 687, in <listcomp>
    self.child.to_representation(item) for item in iterable
  File "/home/mk/python/BUYproject/goods/serializers.py", line 37, in to_representation
    data['prices'] = [price for price in data['prices'] if price['status']]
  File "/home/mk/python/BUYproject/goods/serializers.py", line 37, in <listcomp>
    data['prices'] = [price for price in data['prices'] if price['status']]
KeyError: 'status'
ERROR 2024-05-12 10:30:46,041 basehttp 25116 140217458095680 "GET /api/goods/ HTTP/1.1" 500 125419
INFO 2024-05-12 10:31:28,685 autoreload 25641 140064887768128 Watching for file changes with StatReloader
INFO 2024-05-12 10:31:29,897 basehttp 25641 140064824489536 "GET /api/goods HTTP/1.1" 301 0
INFO 2024-05-12 10:31:29,913 basehttp 25641 140064824489536 "GET /api/goods/ HTTP/1.1" 200 1039
INFO 2024-05-12 10:32:12,344 basehttp 25641 140064824489536 "GET /api/goods HTTP/1.1" 301 0
INFO 2024-05-12 10:32:12,357 basehttp 25641 140064824489536 "GET /api/goods/ HTTP/1.1" 200 1138
INFO 2024-05-12 10:32:50,296 autoreload 25641 140064887768128 /home/mk/python/BUYproject/goods/serializers.py changed, reloading.
INFO 2024-05-12 10:32:50,476 autoreload 26566 140481875694656 Watching for file changes with StatReloader
INFO 2024-05-12 10:32:51,609 autoreload 26566 140481875694656 /home/mk/python/BUYproject/goods/serializers.py changed, reloading.
INFO 2024-05-12 10:32:51,792 autoreload 26599 140324474958912 Watching for file changes with StatReloader
INFO 2024-05-12 10:32:54,381 basehttp 26599 140324411799104 "GET /api/goods HTTP/1.1" 301 0
ERROR 2024-05-12 10:32:54,418 log 26599 140324411799104 Internal Server Error: /api/goods/
Traceback (most recent call last):
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/renderers.py", line 99, in render
    ret = json.dumps(
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/utils/json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/home/mk/anaconda3/envs/web/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/utils/encoders.py", line 67, in default
    return super().default(obj)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type PriceModel is not JSON serializable
ERROR 2024-05-12 10:32:54,418 basehttp 26599 140324411799104 "GET /api/goods/ HTTP/1.1" 500 112816
INFO 2024-05-12 10:33:07,034 autoreload 26599 140324474958912 /home/mk/python/BUYproject/goods/serializers.py changed, reloading.
INFO 2024-05-12 10:33:07,216 autoreload 26784 139780696605760 Watching for file changes with StatReloader
INFO 2024-05-12 10:33:32,486 autoreload 26784 139780696605760 /home/mk/python/BUYproject/goods/serializers.py changed, reloading.
INFO 2024-05-12 10:33:32,665 autoreload 27075 140651107849280 Watching for file changes with StatReloader
INFO 2024-05-12 10:33:44,675 autoreload 27240 140420708672576 Watching for file changes with StatReloader
INFO 2024-05-12 10:33:45,586 basehttp 27240 140420645910080 "GET /api/goods HTTP/1.1" 301 0
INFO 2024-05-12 10:33:45,602 basehttp 27240 140420645910080 "GET /api/goods/ HTTP/1.1" 200 603
INFO 2024-05-12 10:34:14,973 autoreload 27240 140420708672576 /home/mk/python/BUYproject/goods/serializers.py changed, reloading.
INFO 2024-05-12 10:34:15,161 autoreload 27587 140458016314432 Watching for file changes with StatReloader
INFO 2024-05-12 10:34:16,342 basehttp 27587 140457953195584 "GET /api/goods HTTP/1.1" 301 0
INFO 2024-05-12 10:34:16,358 basehttp 27587 140457953195584 "GET /api/goods/ HTTP/1.1" 200 1138
INFO 2024-05-12 10:35:05,672 autoreload 28163 139920280867904 Watching for file changes with StatReloader
INFO 2024-05-12 10:35:07,069 basehttp 28163 139920217732672 "GET /api/goods HTTP/1.1" 301 0
INFO 2024-05-12 10:35:07,087 basehttp 28163 139920217732672 "GET /api/goods/ HTTP/1.1" 200 927
INFO 2024-05-12 10:37:40,474 basehttp 28163 139920217732672 "GET /api/price HTTP/1.1" 301 0
INFO 2024-05-12 10:37:40,486 basehttp 28163 139920217732672 "GET /api/price/ HTTP/1.1" 200 546
INFO 2024-05-12 10:38:05,906 autoreload 30018 139749458478144 Watching for file changes with StatReloader
INFO 2024-05-12 10:38:07,013 basehttp 30018 139749395789376 "GET /api/price HTTP/1.1" 301 0
INFO 2024-05-12 10:38:07,023 basehttp 30018 139749395789376 "GET /api/price/ HTTP/1.1" 200 680
INFO 2024-05-12 10:51:24,667 autoreload 37932 139832281400384 Watching for file changes with StatReloader
WARNING 2024-05-12 10:51:30,747 log 37932 139832218089024 Bad Request: /api/goods/
WARNING 2024-05-12 10:51:30,747 basehttp 37932 139832218089024 "POST /api/goods/ HTTP/1.1" 400 40
WARNING 2024-05-12 10:51:37,198 log 37932 139832218089024 Bad Request: /api/goods/
WARNING 2024-05-12 10:51:37,198 basehttp 37932 139832218089024 "POST /api/goods/ HTTP/1.1" 400 82
INFO 2024-05-12 10:51:46,957 autoreload 37932 139832281400384 /home/mk/python/BUYproject/goods/serializers.py changed, reloading.
INFO 2024-05-12 10:51:47,137 autoreload 38145 140270978819136 Watching for file changes with StatReloader
INFO 2024-05-12 10:51:50,291 autoreload 38194 140157704307776 Watching for file changes with StatReloader
ERROR 2024-05-12 10:51:51,865 log 38194 140157641029184 Internal Server Error: /api/goods/
Traceback (most recent call last):
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/mixins.py", line 19, in create
    self.perform_create(serializer)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/mixins.py", line 24, in perform_create
    serializer.save()
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/serializers.py", line 212, in save
    self.instance = self.create(validated_data)
  File "/home/mk/python/BUYproject/goods/serializers.py", line 31, in create
    PriceModel.objects.create(product=product, start_time=start_time, end_time=end_time, price=price_data, unit=unit_data)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/django/db/models/query.py", line 656, in create
    obj = self.model(**kwargs)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/django/db/models/base.py", line 543, in __init__
    _setattr(self, field.name, rel_obj)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 266, in __set__
    raise ValueError(
ValueError: Cannot assign "1": "PriceModel.unit" must be a "UnitModel" instance.
ERROR 2024-05-12 10:51:51,866 basehttp 38194 140157641029184 "POST /api/goods/ HTTP/1.1" 500 132677
INFO 2024-05-12 10:53:16,673 autoreload 38906 140558975489088 Watching for file changes with StatReloader
INFO 2024-05-12 10:53:18,667 basehttp 38906 140558844556864 "POST /api/goods/ HTTP/1.1" 201 256
INFO 2024-05-12 10:55:56,248 autoreload 40382 139979545179200 Watching for file changes with StatReloader
INFO 2024-05-12 10:55:57,387 basehttp 40382 139979414828608 "GET /api/goods HTTP/1.1" 301 0
ERROR 2024-05-12 10:55:57,427 log 40382 139979414828608 Internal Server Error: /api/goods/
Traceback (most recent call last):
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/mixins.py", line 43, in list
    return self.get_paginated_response(serializer.data)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/serializers.py", line 768, in data
    ret = super().data
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/serializers.py", line 686, in to_representation
    return [
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/serializers.py", line 687, in <listcomp>
    self.child.to_representation(item) for item in iterable
  File "/home/mk/python/BUYproject/goods/serializers.py", line 40, in to_representation
    data['price'] = instance.prices.filter(status=True).first().price
AttributeError: 'NoneType' object has no attribute 'price'
ERROR 2024-05-12 10:55:57,429 basehttp 40382 139979414828608 "GET /api/goods/ HTTP/1.1" 500 120970
INFO 2024-05-12 10:56:15,655 basehttp 40382 139979414828608 "GET /api/goods HTTP/1.1" 301 0
ERROR 2024-05-12 10:56:15,674 log 40382 139979414828608 Internal Server Error: /api/goods/
Traceback (most recent call last):
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/mixins.py", line 43, in list
    return self.get_paginated_response(serializer.data)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/serializers.py", line 768, in data
    ret = super().data
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/serializers.py", line 686, in to_representation
    return [
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/serializers.py", line 687, in <listcomp>
    self.child.to_representation(item) for item in iterable
  File "/home/mk/python/BUYproject/goods/serializers.py", line 40, in to_representation
    data['price'] = instance.prices.filter(status=True).first().price
AttributeError: 'NoneType' object has no attribute 'price'
ERROR 2024-05-12 10:56:15,674 basehttp 40382 139979414828608 "GET /api/goods/ HTTP/1.1" 500 120970
INFO 2024-05-12 10:56:44,256 basehttp 40382 139979414828608 "GET /api/goods HTTP/1.1" 301 0
INFO 2024-05-12 10:56:44,269 basehttp 40382 139979414828608 "GET /api/goods/ HTTP/1.1" 200 308
INFO 2024-05-12 10:57:26,647 basehttp 40382 139979414828608 "PATCH /api/goods/13/ HTTP/1.1" 200 257
INFO 2024-05-12 10:57:29,677 basehttp 40382 139979414828608 "GET /api/goods HTTP/1.1" 301 0
INFO 2024-05-12 10:57:29,689 basehttp 40382 139979414828608 "GET /api/goods/ HTTP/1.1" 200 309
INFO 2024-05-12 10:57:52,885 basehttp 40382 139979414828608 "PATCH /api/goods/13/ HTTP/1.1" 200 257
INFO 2024-05-12 10:57:54,154 basehttp 40382 139979414828608 "PATCH /api/goods/13/ HTTP/1.1" 200 257
INFO 2024-05-12 11:00:04,439 basehttp 40382 139979414828608 "GET /api/price HTTP/1.1" 301 0
INFO 2024-05-12 11:00:04,449 basehttp 40382 139979414828608 "GET /api/price/ HTTP/1.1" 200 186
INFO 2024-05-12 11:00:43,048 autoreload 40382 139979545179200 /home/mk/python/BUYproject/goods/views.py changed, reloading.
INFO 2024-05-12 11:00:43,249 autoreload 43313 140344533312576 Watching for file changes with StatReloader
INFO 2024-05-12 11:00:44,401 autoreload 43313 140344533312576 /home/mk/python/BUYproject/goods/views.py changed, reloading.
INFO 2024-05-12 11:00:44,583 autoreload 43346 139681514533952 Watching for file changes with StatReloader
INFO 2024-05-12 11:02:44,982 autoreload 44561 140564189443136 Watching for file changes with StatReloader
INFO 2024-05-12 11:02:46,421 basehttp 44561 140564126234176 "GET /api/goods HTTP/1.1" 301 0
INFO 2024-05-12 11:02:46,435 basehttp 44561 140564126234176 "GET /api/goods/ HTTP/1.1" 200 309
INFO 2024-05-12 11:03:19,344 autoreload 44561 140564189443136 /home/mk/python/BUYproject/goods/views.py changed, reloading.
INFO 2024-05-12 11:03:19,523 autoreload 44949 140230907929664 Watching for file changes with StatReloader
INFO 2024-05-12 11:03:21,690 autoreload 44949 140230907929664 /home/mk/python/BUYproject/goods/views.py changed, reloading.
INFO 2024-05-12 11:03:21,877 autoreload 44992 140144170869824 Watching for file changes with StatReloader
INFO 2024-05-12 11:03:24,838 autoreload 45021 139836154852416 Watching for file changes with StatReloader
WARNING 2024-05-12 11:03:51,316 log 45021 139836091528768 Bad Request: /api/price/
WARNING 2024-05-12 11:03:51,316 basehttp 45021 139836091528768 "POST /api/price/ HTTP/1.1" 400 40
INFO 2024-05-12 11:04:21,809 basehttp 45021 139836091528768 "POST /api/price/ HTTP/1.1" 201 126
INFO 2024-05-12 11:04:26,961 basehttp 45021 139836091528768 "GET /api/goods HTTP/1.1" 301 0
INFO 2024-05-12 11:04:26,973 basehttp 45021 139836091528768 "GET /api/goods/ HTTP/1.1" 200 309
INFO 2024-05-12 11:04:30,344 basehttp 45021 139836091528768 "GET /api/price HTTP/1.1" 301 0
INFO 2024-05-12 11:04:30,353 basehttp 45021 139836091528768 "GET /api/price/ HTTP/1.1" 200 186
INFO 2024-05-12 11:04:37,106 basehttp 45021 139836091528768 "POST /api/price/ HTTP/1.1" 201 126
INFO 2024-05-12 11:04:46,709 basehttp 45021 139836091528768 "POST /api/price/ HTTP/1.1" 201 125
INFO 2024-05-12 11:04:49,522 basehttp 45021 139836091528768 "GET /api/goods HTTP/1.1" 301 0
INFO 2024-05-12 11:04:49,533 basehttp 45021 139836091528768 "GET /api/goods/ HTTP/1.1" 200 309
INFO 2024-05-12 11:04:52,326 basehttp 45021 139836091528768 "GET /api/price HTTP/1.1" 301 0
INFO 2024-05-12 11:04:52,334 basehttp 45021 139836091528768 "GET /api/price/ HTTP/1.1" 200 186
INFO 2024-05-12 11:16:35,313 autoreload 45021 139836154852416 /home/mk/python/BUYproject/goods/views.py changed, reloading.
INFO 2024-05-12 11:16:35,503 autoreload 52948 139660851340352 Watching for file changes with StatReloader
INFO 2024-05-12 11:17:26,596 autoreload 53511 139809981305920 Watching for file changes with StatReloader
INFO 2024-05-12 11:17:28,437 basehttp 53511 139809842525760 "POST /api/price/ HTTP/1.1" 201 134
INFO 2024-05-12 11:17:33,999 basehttp 53511 139809842525760 "GET /api/goods HTTP/1.1" 301 0
INFO 2024-05-12 11:17:34,012 basehttp 53511 139809842525760 "GET /api/goods/ HTTP/1.1" 200 309
INFO 2024-05-12 11:17:39,036 basehttp 53511 139809842525760 "GET /api/price HTTP/1.1" 301 0
INFO 2024-05-12 11:17:39,045 basehttp 53511 139809842525760 "GET /api/price/ HTTP/1.1" 200 321
INFO 2024-05-12 11:18:01,010 basehttp 53511 139809842525760 "POST /api/price/ HTTP/1.1" 201 135
INFO 2024-05-12 11:18:04,102 basehttp 53511 139809842525760 "POST /api/price/ HTTP/1.1" 201 134
INFO 2024-05-12 11:18:06,637 basehttp 53511 139809842525760 "GET /api/price HTTP/1.1" 301 0
INFO 2024-05-12 11:18:06,647 basehttp 53511 139809842525760 "GET /api/price/ HTTP/1.1" 200 592
INFO 2024-05-12 11:20:26,131 autoreload 55421 139776095974464 Watching for file changes with StatReloader
INFO 2024-05-12 11:20:36,391 basehttp 55421 139776032765504 "POST /api/price/ HTTP/1.1" 201 134
INFO 2024-05-12 11:20:39,485 basehttp 55421 139776032765504 "GET /api/goods HTTP/1.1" 301 0
INFO 2024-05-12 11:20:39,497 basehttp 55421 139776032765504 "GET /api/goods/ HTTP/1.1" 200 306
INFO 2024-05-12 11:20:42,225 basehttp 55421 139776032765504 "GET /api/price HTTP/1.1" 301 0
INFO 2024-05-12 11:20:42,234 basehttp 55421 139776032765504 "GET /api/price/ HTTP/1.1" 200 730
WARNING 2024-05-12 11:20:55,640 log 55421 139776032765504 Bad Request: /api/price/
WARNING 2024-05-12 11:20:55,640 basehttp 55421 139776032765504 "POST /api/price/ HTTP/1.1" 400 60
INFO 2024-05-12 11:21:11,532 autoreload 55421 139776095974464 /home/mk/python/BUYproject/goods/views.py changed, reloading.
INFO 2024-05-12 11:21:11,722 autoreload 55954 140239433774144 Watching for file changes with StatReloader
INFO 2024-05-12 11:21:12,873 autoreload 55954 140239433774144 /home/mk/python/BUYproject/goods/views.py changed, reloading.
INFO 2024-05-12 11:21:13,050 autoreload 55986 139737126384704 Watching for file changes with StatReloader
INFO 2024-05-12 11:21:29,489 autoreload 56172 139706647368768 Watching for file changes with StatReloader
INFO 2024-05-12 11:21:43,672 basehttp 56172 139706584266304 "POST /api/price/ HTTP/1.1" 201 134
INFO 2024-05-12 11:21:46,431 basehttp 56172 139706584266304 "GET /api/goods HTTP/1.1" 301 0
INFO 2024-05-12 11:21:46,445 basehttp 56172 139706584266304 "GET /api/goods/ HTTP/1.1" 200 306
INFO 2024-05-12 11:21:54,739 basehttp 56172 139706584266304 "GET /api/price HTTP/1.1" 301 0
INFO 2024-05-12 11:21:54,749 basehttp 56172 139706584266304 "GET /api/price/ HTTP/1.1" 200 866
INFO 2024-05-12 11:22:38,029 autoreload 56172 139706647368768 /home/mk/python/BUYproject/goods/views.py changed, reloading.
INFO 2024-05-12 11:22:38,213 autoreload 56947 140292642042944 Watching for file changes with StatReloader
INFO 2024-05-12 11:24:14,120 basehttp 56947 140292578866752 "GET /api/goods HTTP/1.1" 301 0
INFO 2024-05-12 11:24:14,133 basehttp 56947 140292578866752 "GET /api/goods/ HTTP/1.1" 200 306
INFO 2024-05-12 11:24:42,058 autoreload 56947 140292642042944 /home/mk/python/BUYproject/goods/serializers.py changed, reloading.
INFO 2024-05-12 11:24:42,244 autoreload 58240 140624890876992 Watching for file changes with StatReloader
INFO 2024-05-12 11:24:43,394 autoreload 58240 140624890876992 /home/mk/python/BUYproject/goods/serializers.py changed, reloading.
INFO 2024-05-12 11:24:43,577 autoreload 58272 139759754482752 Watching for file changes with StatReloader
INFO 2024-05-12 11:24:45,715 autoreload 58272 139759754482752 /home/mk/python/BUYproject/goods/serializers.py changed, reloading.
INFO 2024-05-12 11:24:45,898 autoreload 58301 140658658894912 Watching for file changes with StatReloader
INFO 2024-05-12 11:24:49,057 autoreload 58301 140658658894912 /home/mk/python/BUYproject/goods/serializers.py changed, reloading.
INFO 2024-05-12 11:24:49,239 autoreload 58345 140618951496768 Watching for file changes with StatReloader
INFO 2024-05-12 11:24:51,780 autoreload 58384 139885172438080 Watching for file changes with StatReloader
INFO 2024-05-12 11:25:00,501 basehttp 58384 139885109311040 "POST /api/price/ HTTP/1.1" 201 134
INFO 2024-05-12 11:25:05,165 basehttp 58384 139885109311040 "GET /api/goods HTTP/1.1" 301 0
INFO 2024-05-12 11:25:05,177 basehttp 58384 139885109311040 "GET /api/goods/ HTTP/1.1" 200 306
INFO 2024-05-12 11:31:37,777 basehttp 58384 139885109311040 "GET /api/goods HTTP/1.1" 301 0
INFO 2024-05-12 11:31:37,789 basehttp 58384 139885109311040 "GET /api/goods/ HTTP/1.1" 200 306
INFO 2024-05-12 11:31:52,975 basehttp 58384 139885109311040 "POST /api/goods/ HTTP/1.1" 201 256
INFO 2024-05-12 11:31:55,455 basehttp 58384 139885109311040 "GET /api/goods HTTP/1.1" 301 0
INFO 2024-05-12 11:31:55,468 basehttp 58384 139885109311040 "GET /api/goods/ HTTP/1.1" 200 563
INFO 2024-05-12 11:32:11,058 basehttp 58384 139885109311040 "POST /api/price/ HTTP/1.1" 201 134
INFO 2024-05-12 11:32:13,255 basehttp 58384 139885109311040 "GET /api/goods HTTP/1.1" 301 0
INFO 2024-05-12 11:32:13,269 basehttp 58384 139885109311040 "GET /api/goods/ HTTP/1.1" 200 563
WARNING 2024-05-12 11:32:54,992 log 58384 139885109311040 Not Found: /api/goods/1/
WARNING 2024-05-12 11:32:54,992 basehttp 58384 139885109311040 "PATCH /api/goods/1/ HTTP/1.1" 404 25
INFO 2024-05-12 11:33:18,046 basehttp 58384 139885109311040 "PATCH /api/goods/14/ HTTP/1.1" 200 257
INFO 2024-05-12 11:33:20,701 basehttp 58384 139885109311040 "GET /api/goods HTTP/1.1" 301 0
INFO 2024-05-12 11:33:20,716 basehttp 58384 139885109311040 "GET /api/goods/ HTTP/1.1" 200 564
INFO 2024-05-12 11:34:20,150 autoreload 58384 139885172438080 /home/mk/python/BUYproject/goods/views.py changed, reloading.
INFO 2024-05-12 11:34:20,343 autoreload 64085 140517672608832 Watching for file changes with StatReloader
INFO 2024-05-12 11:34:21,497 autoreload 64085 140517672608832 /home/mk/python/BUYproject/goods/views.py changed, reloading.
INFO 2024-05-12 11:34:21,680 autoreload 64118 140088571888704 Watching for file changes with StatReloader
INFO 2024-05-12 11:34:22,842 autoreload 64118 140088571888704 /home/mk/python/BUYproject/goods/views.py changed, reloading.
INFO 2024-05-12 11:34:23,022 autoreload 64143 140134054761536 Watching for file changes with StatReloader
INFO 2024-05-12 12:22:08,233 autoreload 92541 140114468906048 Watching for file changes with StatReloader
INFO 2024-05-12 12:22:12,568 basehttp 92541 140114405619264 "GET /api/unit HTTP/1.1" 301 0
INFO 2024-05-12 12:22:12,578 basehttp 92541 140114405619264 "GET /api/unit/ HTTP/1.1" 200 167
INFO 2024-05-13 10:34:10,404 autoreload 10106 140375517959232 Watching for file changes with StatReloader
INFO 2024-05-13 10:37:32,072 basehttp 10106 140375454643776 "GET /api/goods HTTP/1.1" 301 0
INFO 2024-05-13 10:37:32,092 basehttp 10106 140375454643776 "GET /api/goods/ HTTP/1.1" 200 564
WARNING 2024-05-13 10:39:16,446 log 10106 140375454643776 Unauthorized: /api/accounts/login/
WARNING 2024-05-13 10:39:16,446 basehttp 10106 140375454643776 "POST /api/accounts/login/ HTTP/1.1" 401 43
WARNING 2024-05-13 10:42:48,496 log 10106 140375454643776 Unauthorized: /api/accounts/login/
WARNING 2024-05-13 10:42:48,496 basehttp 10106 140375454643776 "POST /api/accounts/login/ HTTP/1.1" 401 43
WARNING 2024-05-13 10:43:01,144 log 10106 140375454643776 Method Not Allowed: /api/accounts/login/
WARNING 2024-05-13 10:43:01,144 basehttp 10106 140375454643776 "POST /api/accounts/login/ HTTP/1.1" 405 46
WARNING 2024-05-13 10:44:19,306 log 10106 140375454643776 Unauthorized: /api/accounts/login/
WARNING 2024-05-13 10:44:19,306 basehttp 10106 140375454643776 "POST /api/accounts/login/ HTTP/1.1" 401 43
INFO 2024-05-13 10:46:36,615 basehttp 10106 140375454643776 "POST /api/login/ HTTP/1.1" 200 553
INFO 2024-05-13 10:47:11,010 basehttp 10106 140375454643776 "POST /api/login/ HTTP/1.1" 200 553
WARNING 2024-05-13 10:49:54,295 log 10106 140375454643776 Unauthorized: /api/accounts/
WARNING 2024-05-13 10:49:54,296 basehttp 10106 140375454643776 "GET /api/accounts/ HTTP/1.1" 401 43
INFO 2024-05-13 10:50:24,349 basehttp 10106 140375454643776 "GET /api/accounts/ HTTP/1.1" 200 141
WARNING 2024-05-13 10:51:31,321 log 10106 140375454643776 Unauthorized: /api/accounts/
WARNING 2024-05-13 10:51:31,322 basehttp 10106 140375454643776 "POST /api/accounts/ HTTP/1.1" 401 43
INFO 2024-05-13 10:51:43,956 basehttp 10106 140375454643776 "POST /api/accounts/ HTTP/1.1" 201 70
INFO 2024-05-13 10:51:55,308 basehttp 10106 140375454643776 "POST /api/accounts/ HTTP/1.1" 201 69
INFO 2024-05-13 10:51:58,636 basehttp 10106 140375454643776 "GET /api/accounts/ HTTP/1.1" 200 282
INFO 2024-05-13 10:52:09,131 basehttp 10106 140375454643776 "POST /api/accounts/ HTTP/1.1" 201 70
INFO 2024-05-13 10:52:11,150 basehttp 10106 140375454643776 "GET /api/accounts/ HTTP/1.1" 200 353
INFO 2024-05-13 10:52:27,089 basehttp 10106 140375454643776 "POST /api/login/ HTTP/1.1" 200 553
INFO 2024-05-13 11:09:31,837 autoreload 31600 140161052406848 Watching for file changes with StatReloader
INFO 2024-05-13 11:09:47,734 basehttp 31600 140160989132352 "GET /api/goods HTTP/1.1" 301 0
ERROR 2024-05-13 11:09:47,758 log 31600 140160989132352 Internal Server Error: /api/goods/
Traceback (most recent call last):
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/views.py", line 415, in initial
    self.check_permissions(request)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/views.py", line 332, in check_permissions
    if not permission.has_permission(request, self):
  File "/home/mk/python/BUYproject/goods/permissions.py", line 5, in has_permission
    return request.user.role == 0
AttributeError: 'AnonymousUser' object has no attribute 'role'
ERROR 2024-05-13 11:09:47,758 basehttp 31600 140160989132352 "GET /api/goods/ HTTP/1.1" 500 103579
INFO 2024-05-13 11:10:53,856 autoreload 32336 140522513044544 Watching for file changes with StatReloader
INFO 2024-05-13 11:10:55,406 basehttp 32336 140522449794624 "GET /api/goods HTTP/1.1" 301 0
ERROR 2024-05-13 11:10:55,419 log 32336 140522449794624 Internal Server Error: /api/goods/
Traceback (most recent call last):
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/views.py", line 415, in initial
    self.check_permissions(request)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/views.py", line 332, in check_permissions
    if not permission.has_permission(request, self):
  File "/home/mk/python/BUYproject/goods/permissions.py", line 5, in has_permission
    return request.user.role == 0
AttributeError: 'AnonymousUser' object has no attribute 'role'
ERROR 2024-05-13 11:10:55,419 basehttp 32336 140522449794624 "GET /api/goods/ HTTP/1.1" 500 103586
INFO 2024-05-13 11:11:06,942 basehttp 32336 140522449794624 "GET /api/goods HTTP/1.1" 301 0
ERROR 2024-05-13 11:11:06,955 log 32336 140522449794624 Internal Server Error: /api/goods/
Traceback (most recent call last):
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/views.py", line 415, in initial
    self.check_permissions(request)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/views.py", line 332, in check_permissions
    if not permission.has_permission(request, self):
  File "/home/mk/python/BUYproject/goods/permissions.py", line 5, in has_permission
    return request.user.role == 0
AttributeError: 'AnonymousUser' object has no attribute 'role'
ERROR 2024-05-13 11:11:06,955 basehttp 32336 140522449794624 "GET /api/goods/ HTTP/1.1" 500 103586
INFO 2024-05-13 11:11:10,364 basehttp 32336 140522449794624 "GET /api/price HTTP/1.1" 301 0
ERROR 2024-05-13 11:11:10,376 log 32336 140522449794624 Internal Server Error: /api/price/
Traceback (most recent call last):
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/views.py", line 415, in initial
    self.check_permissions(request)
  File "/home/mk/anaconda3/envs/web/lib/python3.9/site-packages/rest_framework/views.py", line 332, in check_permissions
    if not permission.has_permission(request, self):
  File "/home/mk/python/BUYproject/goods/permissions.py", line 5, in has_permission
    return request.user.role == 0
AttributeError: 'AnonymousUser' object has no attribute 'role'
ERROR 2024-05-13 11:11:10,376 basehttp 32336 140522449794624 "GET /api/price/ HTTP/1.1" 500 103586
INFO 2024-05-13 11:13:42,881 autoreload 33757 139699582100544 Watching for file changes with StatReloader
INFO 2024-05-13 11:13:44,656 basehttp 33757 139699448444480 "GET /api/price HTTP/1.1" 301 0
WARNING 2024-05-13 11:13:44,660 log 33757 139699448444480 Unauthorized: /api/price/
WARNING 2024-05-13 11:13:44,660 basehttp 33757 139699448444480 "GET /api/price/ HTTP/1.1" 401 43
INFO 2024-05-13 11:13:49,802 basehttp 33757 139699448444480 "GET /api/goods HTTP/1.1" 301 0
WARNING 2024-05-13 11:13:49,805 log 33757 139699448444480 Unauthorized: /api/goods/
WARNING 2024-05-13 11:13:49,805 basehttp 33757 139699448444480 "GET /api/goods/ HTTP/1.1" 401 43
INFO 2024-05-13 11:14:06,581 basehttp 33757 139699448444480 "GET /api/goods HTTP/1.1" 301 0
WARNING 2024-05-13 11:14:06,592 log 33757 139699448444480 Forbidden: /api/goods/
WARNING 2024-05-13 11:14:06,592 basehttp 33757 139699448444480 "GET /api/goods/ HTTP/1.1" 403 49
INFO 2024-05-13 11:14:17,306 basehttp 33757 139699448444480 "POST /api/login/ HTTP/1.1" 200 553
INFO 2024-05-13 11:14:26,694 basehttp 33757 139699448444480 "GET /api/goods HTTP/1.1" 301 0
WARNING 2024-05-13 11:14:26,701 log 33757 139699448444480 Forbidden: /api/goods/
WARNING 2024-05-13 11:14:26,702 basehttp 33757 139699448444480 "GET /api/goods/ HTTP/1.1" 403 49
INFO 2024-05-13 11:16:31,475 autoreload 35440 139769697137728 Watching for file changes with StatReloader
INFO 2024-05-13 11:16:37,789 basehttp 35440 139769566459456 "GET /api/goods HTTP/1.1" 301 0
WARNING 2024-05-13 11:16:37,799 log 35440 139769566459456 Forbidden: /api/goods/
WARNING 2024-05-13 11:16:37,799 basehttp 35440 139769566459456 "GET /api/goods/ HTTP/1.1" 403 49
INFO 2024-05-13 11:16:43,687 basehttp 35440 139769566459456 "POST /api/login/ HTTP/1.1" 200 553
INFO 2024-05-13 11:16:55,033 basehttp 35440 139769566459456 "GET /api/goods HTTP/1.1" 301 0
WARNING 2024-05-13 11:16:55,041 log 35440 139769566459456 Forbidden: /api/goods/
WARNING 2024-05-13 11:16:55,041 basehttp 35440 139769566459456 "GET /api/goods/ HTTP/1.1" 403 49
INFO 2024-05-13 11:17:04,222 basehttp 35440 139769566459456 "POST /api/login/ HTTP/1.1" 200 552
INFO 2024-05-13 11:17:11,339 basehttp 35440 139769566459456 "GET /api/goods HTTP/1.1" 301 0
WARNING 2024-05-13 11:17:11,346 log 35440 139769566459456 Forbidden: /api/goods/
WARNING 2024-05-13 11:17:11,346 basehttp 35440 139769566459456 "GET /api/goods/ HTTP/1.1" 403 49
INFO 2024-05-13 11:17:58,156 autoreload 35440 139769697137728 /home/mk/python/BUYproject/goods/permissions.py changed, reloading.
INFO 2024-05-13 11:17:58,342 autoreload 36367 139891079238720 Watching for file changes with StatReloader
INFO 2024-05-13 11:17:59,491 autoreload 36367 139891079238720 /home/mk/python/BUYproject/goods/permissions.py changed, reloading.
INFO 2024-05-13 11:17:59,675 autoreload 36394 139911657706560 Watching for file changes with StatReloader
INFO 2024-05-13 11:18:00,827 autoreload 36394 139911657706560 /home/mk/python/BUYproject/goods/permissions.py changed, reloading.
INFO 2024-05-13 11:18:01,015 autoreload 36419 139903405212736 Watching for file changes with StatReloader
INFO 2024-05-13 11:18:07,348 basehttp 36419 139903341950528 "GET /api/goods HTTP/1.1" 301 0
WARNING 2024-05-13 11:18:07,358 log 36419 139903341950528 Forbidden: /api/goods/
WARNING 2024-05-13 11:18:07,358 basehttp 36419 139903341950528 "GET /api/goods/ HTTP/1.1" 403 49
INFO 2024-05-13 11:18:17,278 autoreload 36419 139903405212736 /home/mk/python/BUYproject/goods/permissions.py changed, reloading.
INFO 2024-05-13 11:18:17,479 autoreload 36628 140521189446720 Watching for file changes with StatReloader
INFO 2024-05-13 11:18:18,773 basehttp 36628 140521059120704 "GET /api/goods HTTP/1.1" 301 0
WARNING 2024-05-13 11:18:18,783 log 36628 140521059120704 Forbidden: /api/goods/
WARNING 2024-05-13 11:18:18,783 basehttp 36628 140521059120704 "GET /api/goods/ HTTP/1.1" 403 49
INFO 2024-05-13 11:18:25,679 autoreload 36628 140521189446720 /home/mk/python/BUYproject/goods/permissions.py changed, reloading.
INFO 2024-05-13 11:18:25,865 autoreload 36737 140473424348224 Watching for file changes with StatReloader
INFO 2024-05-13 11:18:27,324 basehttp 36737 140473361233472 "GET /api/goods HTTP/1.1" 301 0
WARNING 2024-05-13 11:18:27,334 log 36737 140473361233472 Forbidden: /api/goods/
WARNING 2024-05-13 11:18:27,334 basehttp 36737 140473361233472 "GET /api/goods/ HTTP/1.1" 403 49
INFO 2024-05-13 11:18:29,342 basehttp 36737 140473361233472 "GET /api/goods HTTP/1.1" 301 0
WARNING 2024-05-13 11:18:29,351 log 36737 140473361233472 Forbidden: /api/goods/
WARNING 2024-05-13 11:18:29,352 basehttp 36737 140473361233472 "GET /api/goods/ HTTP/1.1" 403 49
INFO 2024-05-13 11:19:20,327 autoreload 36737 140473424348224 /home/mk/python/BUYproject/goods/views.py changed, reloading.
INFO 2024-05-13 11:19:20,512 autoreload 37180 139873251124288 Watching for file changes with StatReloader
INFO 2024-05-13 11:19:35,572 basehttp 37180 139873120417344 "POST /api/login/ HTTP/1.1" 200 553
INFO 2024-05-13 11:19:42,308 basehttp 37180 139873120417344 "GET /api/goods HTTP/1.1" 301 0
WARNING 2024-05-13 11:19:42,316 log 37180 139873120417344 Forbidden: /api/goods/
WARNING 2024-05-13 11:19:42,316 basehttp 37180 139873120417344 "GET /api/goods/ HTTP/1.1" 403 49
INFO 2024-05-13 11:19:52,851 autoreload 37180 139873251124288 /home/mk/python/BUYproject/goods/permissions.py changed, reloading.
INFO 2024-05-13 11:19:53,040 autoreload 37480 140299096708160 Watching for file changes with StatReloader
INFO 2024-05-13 11:19:55,192 autoreload 37480 140299096708160 /home/mk/python/BUYproject/goods/permissions.py changed, reloading.
INFO 2024-05-13 11:19:55,382 autoreload 37520 140208928953408 Watching for file changes with StatReloader
INFO 2024-05-13 11:19:56,942 basehttp 37520 140208798430784 "GET /api/goods HTTP/1.1" 301 0
WARNING 2024-05-13 11:19:56,954 log 37520 140208798430784 Forbidden: /api/goods/
WARNING 2024-05-13 11:19:56,954 basehttp 37520 140208798430784 "GET /api/goods/ HTTP/1.1" 403 49
INFO 2024-05-13 11:20:52,864 autoreload 37520 140208928953408 /home/mk/python/BUYproject/goods/views.py changed, reloading.
INFO 2024-05-13 11:20:53,050 autoreload 37958 140017863255104 Watching for file changes with StatReloader
INFO 2024-05-13 11:20:55,169 basehttp 37958 140017800050240 "GET /api/goods HTTP/1.1" 301 0
INFO 2024-05-13 11:20:55,187 basehttp 37958 140017800050240 "GET /api/goods/ HTTP/1.1" 200 564
INFO 2024-05-13 11:21:05,900 basehttp 37958 140017800050240 "POST /api/login/ HTTP/1.1" 200 552
INFO 2024-05-13 11:21:13,241 basehttp 37958 140017800050240 "GET /api/goods HTTP/1.1" 301 0
INFO 2024-05-13 11:21:13,255 basehttp 37958 140017800050240 "GET /api/goods/ HTTP/1.1" 200 564
INFO 2024-05-13 11:21:32,552 basehttp 37958 140017800050240 "POST /api/login/ HTTP/1.1" 200 553
INFO 2024-05-13 11:21:38,785 basehttp 37958 140017800050240 "GET /api/goods HTTP/1.1" 301 0
WARNING 2024-05-13 11:21:38,793 log 37958 140017800050240 Forbidden: /api/goods/
WARNING 2024-05-13 11:21:38,793 basehttp 37958 140017800050240 "GET /api/goods/ HTTP/1.1" 403 49
INFO 2024-05-13 11:22:19,806 autoreload 38722 140108517114944 Watching for file changes with StatReloader
INFO 2024-05-13 11:23:44,410 autoreload 38722 140108517114944 /home/mk/python/BUYproject/account/serializers.py changed, reloading.
INFO 2024-05-13 11:23:44,585 autoreload 39354 140129480512576 Watching for file changes with StatReloader
WARNING 2024-05-13 11:23:52,313 log 39354 140129347827264 Method Not Allowed: /api/accounts/
WARNING 2024-05-13 11:23:52,313 basehttp 39354 140129347827264 "PUT /api/accounts/ HTTP/1.1" 405 45
WARNING 2024-05-13 11:24:02,831 log 39354 140129347827264 Method Not Allowed: /api/accounts/
WARNING 2024-05-13 11:24:02,832 basehttp 39354 140129347827264 "PUT /api/accounts/ HTTP/1.1" 405 45
WARNING 2024-05-13 11:24:25,115 log 39354 140129347827264 Method Not Allowed: /api/accounts/
WARNING 2024-05-13 11:24:25,115 basehttp 39354 140129347827264 "PUT /api/accounts/ HTTP/1.1" 405 45
WARNING 2024-05-13 11:25:18,183 log 39354 140129347827264 Bad Request: /api/accounts/4/
WARNING 2024-05-13 11:25:18,183 basehttp 39354 140129347827264 "PUT /api/accounts/4/ HTTP/1.1" 400 37
INFO 2024-05-13 11:26:09,573 autoreload 39354 140129480512576 /home/mk/python/BUYproject/account/serializers.py changed, reloading.
INFO 2024-05-13 11:26:09,769 autoreload 40627 140602597475392 Watching for file changes with StatReloader
WARNING 2024-05-13 11:26:12,719 log 40627 140602465318464 Bad Request: /api/accounts/4/
WARNING 2024-05-13 11:26:12,719 basehttp 40627 140602465318464 "PUT /api/accounts/4/ HTTP/1.1" 400 37
WARNING 2024-05-13 11:26:13,954 log 40627 140602465318464 Bad Request: /api/accounts/4/
WARNING 2024-05-13 11:26:13,955 basehttp 40627 140602465318464 "PUT /api/accounts/4/ HTTP/1.1" 400 37
INFO 2024-05-13 11:29:42,153 autoreload 40627 140602597475392 /home/mk/python/BUYproject/account/serializers.py changed, reloading.
INFO 2024-05-13 11:29:42,342 autoreload 42466 140085208372288 Watching for file changes with StatReloader
WARNING 2024-05-13 11:29:46,715 log 42466 140085145105984 Bad Request: /api/accounts/4/
WARNING 2024-05-13 11:29:46,716 basehttp 42466 140085145105984 "PUT /api/accounts/4/ HTTP/1.1" 400 37
WARNING 2024-05-13 11:29:47,840 log 42466 140085145105984 Bad Request: /api/accounts/4/
WARNING 2024-05-13 11:29:47,840 basehttp 42466 140085145105984 "PUT /api/accounts/4/ HTTP/1.1" 400 37
INFO 2024-05-13 11:29:53,581 autoreload 42466 140085208372288 /home/mk/python/BUYproject/account/serializers.py changed, reloading.
INFO 2024-05-13 11:29:53,766 autoreload 42595 140630050452544 Watching for file changes with StatReloader
INFO 2024-05-13 11:29:55,922 autoreload 42595 140630050452544 /home/mk/python/BUYproject/account/serializers.py changed, reloading.
INFO 2024-05-13 11:29:56,105 autoreload 42636 139662073697344 Watching for file changes with StatReloader
INFO 2024-05-13 11:29:59,258 autoreload 42636 139662073697344 /home/mk/python/BUYproject/account/serializers.py changed, reloading.
INFO 2024-05-13 11:29:59,449 autoreload 42666 139944064046144 Watching for file changes with StatReloader
INFO 2024-05-13 11:30:01,610 autoreload 42666 139944064046144 /home/mk/python/BUYproject/account/serializers.py changed, reloading.
INFO 2024-05-13 11:30:01,802 autoreload 42701 140189866484800 Watching for file changes with StatReloader
INFO 2024-05-13 11:30:05,954 autoreload 42701 140189866484800 /home/mk/python/BUYproject/account/serializers.py changed, reloading.
INFO 2024-05-13 11:30:06,142 autoreload 42759 140515166798912 Watching for file changes with StatReloader
INFO 2024-05-13 11:30:08,383 basehttp 42759 140515103471168 "PUT /api/accounts/4/ HTTP/1.1" 200 87
WARNING 2024-05-13 11:30:16,454 log 42759 140515103471168 Bad Request: /api/login/
WARNING 2024-05-13 11:30:16,454 basehttp 42759 140515103471168 "POST /api/login/ HTTP/1.1" 400 34
INFO 2024-05-13 11:30:19,794 basehttp 42759 140515103471168 "POST /api/login/ HTTP/1.1" 200 554
INFO 2024-05-13 11:30:35,513 autoreload 42759 140515166798912 /home/mk/python/BUYproject/account/serializers.py changed, reloading.
INFO 2024-05-13 11:30:35,699 autoreload 43001 139881086354496 Watching for file changes with StatReloader
INFO 2024-05-13 11:31:29,919 autoreload 43437 140641368056896 Watching for file changes with StatReloader
INFO 2024-05-13 11:31:31,378 basehttp 43437 140641304835648 "POST /api/accounts/ HTTP/1.1" 201 70
INFO 2024-05-13 11:34:16,833 autoreload 45103 140531152999488 Watching for file changes with StatReloader
WARNING 2024-05-13 11:34:18,223 log 45103 140531089798720 Bad Request: /api/accounts/
WARNING 2024-05-13 11:34:18,223 basehttp 45103 140531089798720 "POST /api/accounts/ HTTP/1.1" 400 59
WARNING 2024-05-13 11:34:22,829 log 45103 140531089798720 Bad Request: /api/accounts/
WARNING 2024-05-13 11:34:22,829 basehttp 45103 140531089798720 "POST /api/accounts/ HTTP/1.1" 400 25
WARNING 2024-05-13 11:41:35,982 log 45103 140531089798720 Bad Request: /api/accounts/
WARNING 2024-05-13 11:41:35,982 basehttp 45103 140531089798720 "POST /api/accounts/ HTTP/1.1" 400 25
INFO 2024-05-13 11:44:26,124 autoreload 51020 140419766154304 Watching for file changes with StatReloader
INFO 2024-05-13 11:44:27,967 basehttp 51020 140419702978112 "POST /api/login/ HTTP/1.1" 200 554
INFO 2024-05-17 12:02:24,503 autoreload 17381 139983684531264 Watching for file changes with StatReloader
INFO 2024-05-17 12:02:30,983 basehttp 17381 139983619880512 "GET /api/accounts/ HTTP/1.1" 200 124
INFO 2024-05-17 12:16:41,310 autoreload 20031 140673414173760 Watching for file changes with StatReloader
INFO 2024-05-17 12:16:45,031 basehttp 20031 140673349056064 "POST /api/accounts/ HTTP/1.1" 201 69
INFO 2024-05-17 12:16:57,528 basehttp 20031 140673349056064 "POST /api/accounts/ HTTP/1.1" 201 70
INFO 2024-05-17 12:17:04,442 basehttp 20031 140673349056064 "POST /api/accounts/ HTTP/1.1" 201 70
INFO 2024-05-17 12:17:19,295 basehttp 20031 140673349056064 "POST /api/login/ HTTP/1.1" 200 553
INFO 2024-05-17 12:17:41,119 basehttp 20031 140673349056064 "GET /api/goods HTTP/1.1" 301 0
WARNING 2024-05-17 12:17:41,126 log 20031 140673349056064 Unauthorized: /api/goods/
WARNING 2024-05-17 12:17:41,126 basehttp 20031 140673349056064 "GET /api/goods/ HTTP/1.1" 401 43
INFO 2024-05-17 12:17:45,981 basehttp 20031 140673349056064 "GET /api/goods HTTP/1.1" 301 0
WARNING 2024-05-17 12:17:45,989 log 20031 140673349056064 Unauthorized: /api/goods/
WARNING 2024-05-17 12:17:45,989 basehttp 20031 140673349056064 "GET /api/goods/ HTTP/1.1" 401 173
INFO 2024-05-17 12:18:02,746 basehttp 20031 140673349056064 "GET /api/goods HTTP/1.1" 301 0
INFO 2024-05-17 12:18:02,773 basehttp 20031 140673349056064 "GET /api/goods/ HTTP/1.1" 200 52
INFO 2024-05-17 12:18:11,441 basehttp 20031 140673349056064 "GET /api/price HTTP/1.1" 301 0
WARNING 2024-05-17 12:18:11,459 log 20031 140673349056064 Forbidden: /api/price/
WARNING 2024-05-17 12:18:11,459 basehttp 20031 140673349056064 "GET /api/price/ HTTP/1.1" 403 49
ERROR 2024-05-17 12:18:23,008 log 20031 140673349056064 Internal Server Error: /api/goods/
Traceback (most recent call last):
  File "/home/mk/anaconda3/envs/buyweb/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/mk/anaconda3/envs/buyweb/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mk/anaconda3/envs/buyweb/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/home/mk/anaconda3/envs/buyweb/lib/python3.10/site-packages/rest_framework/viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/mk/anaconda3/envs/buyweb/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/mk/anaconda3/envs/buyweb/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/mk/anaconda3/envs/buyweb/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/mk/anaconda3/envs/buyweb/lib/python3.10/site-packages/rest_framework/views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "/home/mk/anaconda3/envs/buyweb/lib/python3.10/site-packages/rest_framework/views.py", line 415, in initial
    self.check_permissions(request)
  File "/home/mk/anaconda3/envs/buyweb/lib/python3.10/site-packages/rest_framework/views.py", line 332, in check_permissions
    if not permission.has_permission(request, self):
TypeError: IsRole0.has_permission() missing 1 required positional argument: 'view'
ERROR 2024-05-17 12:18:23,009 basehttp 20031 140673349056064 "POST /api/goods/ HTTP/1.1" 500 99541
ERROR 2024-05-17 12:21:30,874 log 20031 140673349056064 Internal Server Error: /api/goods/
Traceback (most recent call last):
  File "/home/mk/anaconda3/envs/buyweb/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/mk/anaconda3/envs/buyweb/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mk/anaconda3/envs/buyweb/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/home/mk/anaconda3/envs/buyweb/lib/python3.10/site-packages/rest_framework/viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/mk/anaconda3/envs/buyweb/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/mk/anaconda3/envs/buyweb/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/mk/anaconda3/envs/buyweb/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/mk/anaconda3/envs/buyweb/lib/python3.10/site-packages/rest_framework/views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "/home/mk/anaconda3/envs/buyweb/lib/python3.10/site-packages/rest_framework/views.py", line 415, in initial
    self.check_permissions(request)
  File "/home/mk/anaconda3/envs/buyweb/lib/python3.10/site-packages/rest_framework/views.py", line 332, in check_permissions
    if not permission.has_permission(request, self):
TypeError: IsRole0.has_permission() missing 1 required positional argument: 'view'
ERROR 2024-05-17 12:21:30,875 basehttp 20031 140673349056064 "POST /api/goods/ HTTP/1.1" 500 99894
INFO 2024-05-17 12:23:46,841 autoreload 21446 139629330555968 Watching for file changes with StatReloader
ERROR 2024-05-17 12:23:50,099 log 21446 139629266204224 Internal Server Error: /api/goods/
Traceback (most recent call last):
  File "/home/mk/anaconda3/envs/buyweb/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/mk/anaconda3/envs/buyweb/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mk/anaconda3/envs/buyweb/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/home/mk/anaconda3/envs/buyweb/lib/python3.10/site-packages/rest_framework/viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/mk/anaconda3/envs/buyweb/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/mk/anaconda3/envs/buyweb/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/mk/anaconda3/envs/buyweb/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/mk/anaconda3/envs/buyweb/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/mk/anaconda3/envs/buyweb/lib/python3.10/site-packages/rest_framework/mixins.py", line 19, in create
    self.perform_create(serializer)
  File "/home/mk/anaconda3/envs/buyweb/lib/python3.10/site-packages/rest_framework/mixins.py", line 24, in perform_create
    serializer.save()
  File "/home/mk/anaconda3/envs/buyweb/lib/python3.10/site-packages/rest_framework/serializers.py", line 208, in save
    self.instance = self.create(validated_data)
  File "/home/mk/python/BUYproject/goods/serializers.py", line 36, in create
    unit = UnitModel.objects.get(id=unit_data)
  File "/home/mk/anaconda3/envs/buyweb/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/mk/anaconda3/envs/buyweb/lib/python3.10/site-packages/django/db/models/query.py", line 649, in get
    raise self.model.DoesNotExist(
goods.models.UnitModel.DoesNotExist: UnitModel matching query does not exist.
ERROR 2024-05-17 12:23:50,100 basehttp 21446 139629266204224 "POST /api/goods/ HTTP/1.1" 500 120725
WARNING 2024-05-17 12:25:02,313 log 21446 139629266204224 Unauthorized: /api/unit/
WARNING 2024-05-17 12:25:02,313 basehttp 21446 139629266204224 "GET /api/unit/ HTTP/1.1" 401 43
WARNING 2024-05-17 12:25:20,820 log 21446 139629266204224 Forbidden: /api/unit/
WARNING 2024-05-17 12:25:20,820 basehttp 21446 139629266204224 "GET /api/unit/ HTTP/1.1" 403 49
INFO 2024-05-17 12:25:28,568 basehttp 21446 139629266204224 "POST /api/login/ HTTP/1.1" 200 553
INFO 2024-05-17 12:25:37,952 basehttp 21446 139629266204224 "GET /api/unit/ HTTP/1.1" 200 52
INFO 2024-05-17 12:25:44,161 basehttp 21446 139629266204224 "POST /api/unit/ HTTP/1.1" 201 24
INFO 2024-05-17 12:25:49,603 basehttp 21446 139629266204224 "POST /api/unit/ HTTP/1.1" 201 21
INFO 2024-05-17 12:25:54,598 basehttp 21446 139629266204224 "POST /api/unit/ HTTP/1.1" 201 24
INFO 2024-05-17 12:25:59,866 basehttp 21446 139629266204224 "POST /api/unit/ HTTP/1.1" 201 21
INFO 2024-05-17 12:26:05,499 basehttp 21446 139629266204224 "POST /api/unit/ HTTP/1.1" 201 21
INFO 2024-05-17 12:26:31,413 basehttp 21446 139629266204224 "POST /api/goods/ HTTP/1.1" 201 253
INFO 2024-05-17 12:26:38,628 basehttp 21446 139629266204224 "GET /api/goods HTTP/1.1" 301 0
ERROR 2024-05-17 12:26:38,685 log 21446 139629266204224 Internal Server Error: /api/goods/
Traceback (most recent call last):
  File "/home/mk/anaconda3/envs/buyweb/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/mk/anaconda3/envs/buyweb/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mk/anaconda3/envs/buyweb/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/home/mk/anaconda3/envs/buyweb/lib/python3.10/site-packages/rest_framework/viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/mk/anaconda3/envs/buyweb/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/mk/anaconda3/envs/buyweb/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/mk/anaconda3/envs/buyweb/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/mk/anaconda3/envs/buyweb/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/mk/anaconda3/envs/buyweb/lib/python3.10/site-packages/rest_framework/mixins.py", line 43, in list
    return self.get_paginated_response(serializer.data)
  File "/home/mk/anaconda3/envs/buyweb/lib/python3.10/site-packages/rest_framework/serializers.py", line 795, in data
    ret = super().data
  File "/home/mk/anaconda3/envs/buyweb/lib/python3.10/site-packages/rest_framework/serializers.py", line 249, in data
    self._data = self.to_representation(self.instance)
  File "/home/mk/anaconda3/envs/buyweb/lib/python3.10/site-packages/rest_framework/serializers.py", line 713, in to_representation
    return [
  File "/home/mk/anaconda3/envs/buyweb/lib/python3.10/site-packages/rest_framework/serializers.py", line 714, in <listcomp>
    self.child.to_representation(item) for item in iterable
  File "/home/mk/python/BUYproject/goods/serializers.py", line 46, in to_representation
    data['price'] = instance.prices.filter(status=True).first().price
AttributeError: 'NoneType' object has no attribute 'price'
ERROR 2024-05-17 12:26:38,686 basehttp 21446 139629266204224 "GET /api/goods/ HTTP/1.1" 500 119636
INFO 2024-05-17 12:26:57,565 basehttp 21446 139629266204224 "GET /api/goods HTTP/1.1" 301 0
INFO 2024-05-17 12:26:57,597 basehttp 21446 139629266204224 "GET /api/goods/ HTTP/1.1" 200 305
INFO 2024-05-17 12:27:04,332 basehttp 21446 139629266204224 "GET /api/price HTTP/1.1" 301 0
WARNING 2024-05-17 12:27:04,356 log 21446 139629266204224 Forbidden: /api/price/
WARNING 2024-05-17 12:27:04,356 basehttp 21446 139629266204224 "GET /api/price/ HTTP/1.1" 403 49
INFO 2024-05-17 12:27:08,866 basehttp 21446 139629266204224 "GET /api/price HTTP/1.1" 301 0
INFO 2024-05-17 12:27:08,893 basehttp 21446 139629266204224 "GET /api/price/ HTTP/1.1" 200 185
WARNING 2024-05-17 12:27:35,172 log 21446 139629266204224 Unauthorized: /api/price/
WARNING 2024-05-17 12:27:35,172 basehttp 21446 139629266204224 "POST /api/price/ HTTP/1.1" 401 43
INFO 2024-05-17 12:27:40,827 basehttp 21446 139629266204224 "POST /api/price/ HTTP/1.1" 201 133
INFO 2024-05-17 12:27:44,648 basehttp 21446 139629266204224 "GET /api/goods HTTP/1.1" 301 0
INFO 2024-05-17 12:27:44,680 basehttp 21446 139629266204224 "GET /api/goods/ HTTP/1.1" 200 305
INFO 2024-05-17 13:19:55,027 basehttp 21446 139629266204224 "GET /api/price HTTP/1.1" 301 0
INFO 2024-05-17 13:19:55,060 basehttp 21446 139629266204224 "GET /api/price/ HTTP/1.1" 200 320
INFO 2024-05-17 15:09:02,244 autoreload 39198 140335659713600 Watching for file changes with StatReloader
INFO 2024-05-17 15:09:27,531 basehttp 39198 140335595386432 "POST /api/accounts/ HTTP/1.1" 201 53
INFO 2024-05-17 15:09:35,022 basehttp 39198 140335595386432 "POST /api/accounts/ HTTP/1.1" 201 53
WARNING 2024-05-17 15:15:06,780 log 39198 140335595386432 Unauthorized: /api/accounts/4/
WARNING 2024-05-17 15:15:06,781 basehttp 39198 140335595386432 "PATCH /api/accounts/4/ HTTP/1.1" 401 43
WARNING 2024-05-17 15:15:24,056 log 39198 140335595386432 Forbidden: /api/accounts/4/
WARNING 2024-05-17 15:15:24,057 basehttp 39198 140335595386432 "PATCH /api/accounts/4/ HTTP/1.1" 403 49
INFO 2024-05-17 15:15:32,078 basehttp 39198 140335595386432 "POST /api/login/ HTTP/1.1" 200 553
WARNING 2024-05-17 15:15:43,342 log 39198 140335595386432 Forbidden: /api/accounts/4/
WARNING 2024-05-17 15:15:43,343 basehttp 39198 140335595386432 "PATCH /api/accounts/4/ HTTP/1.1" 403 49
INFO 2024-05-17 17:47:24,561 basehttp 39198 140335595386432 "GET /api/accounts/ HTTP/1.1" 200 372
WARNING 2024-05-17 17:47:50,141 log 39198 140335595386432 Forbidden: /api/accounts/4/
WARNING 2024-05-17 17:47:50,142 basehttp 39198 140335595386432 "PATCH /api/accounts/4/ HTTP/1.1" 403 49
WARNING 2024-05-17 17:48:16,363 log 39198 140335595386432 Forbidden: /api/accounts/4/
WARNING 2024-05-17 17:48:16,364 basehttp 39198 140335595386432 "PATCH /api/accounts/4/ HTTP/1.1" 403 49
INFO 2024-05-17 17:48:25,009 basehttp 39198 140335595386432 "PUT /api/accounts/4/ HTTP/1.1" 200 52
WARNING 2024-05-17 17:48:29,842 log 39198 140335595386432 Bad Request: /api/login/
WARNING 2024-05-17 17:48:29,843 basehttp 39198 140335595386432 "POST /api/login/ HTTP/1.1" 400 34
INFO 2024-05-17 17:48:34,762 basehttp 39198 140335595386432 "POST /api/login/ HTTP/1.1" 200 554
WARNING 2024-05-17 17:53:11,575 log 39198 140335595386432 Forbidden: /api/accounts/2/
WARNING 2024-05-17 17:53:11,575 basehttp 39198 140335595386432 "PUT /api/accounts/2/ HTTP/1.1" 403 49
INFO 2024-05-17 17:53:42,442 basehttp 39198 140335595386432 "PUT /api/accounts/4/ HTTP/1.1" 200 52
INFO 2024-05-17 17:56:31,841 basehttp 39198 140335595386432 "POST /api/login/ HTTP/1.1" 200 553
INFO 2024-05-17 17:56:38,887 basehttp 39198 140335595386432 "PUT /api/accounts/4/ HTTP/1.1" 200 52
INFO 2024-05-17 17:56:46,681 basehttp 39198 140335595386432 "POST /api/login/ HTTP/1.1" 200 554
WARNING 2024-05-17 17:56:53,253 log 39198 140335595386432 Unauthorized: /api/accounts/4/
WARNING 2024-05-17 17:56:53,254 basehttp 39198 140335595386432 "PATCH /api/accounts/4/ HTTP/1.1" 401 43
INFO 2024-05-17 17:57:10,382 basehttp 39198 140335595386432 "POST /api/login/ HTTP/1.1" 200 553
INFO 2024-05-17 17:57:19,220 basehttp 39198 140335595386432 "PATCH /api/accounts/4/ HTTP/1.1" 200 52
WARNING 2024-05-17 17:57:28,617 log 39198 140335595386432 Bad Request: /api/login/
WARNING 2024-05-17 17:57:28,617 basehttp 39198 140335595386432 "POST /api/login/ HTTP/1.1" 400 34
INFO 2024-05-17 17:57:32,383 basehttp 39198 140335595386432 "POST /api/login/ HTTP/1.1" 200 553
INFO 2024-05-17 18:14:56,071 basehttp 39198 140335595386432 "GET /api/goods HTTP/1.1" 301 0
INFO 2024-05-17 18:14:56,117 basehttp 39198 140335595386432 "GET /api/goods/ HTTP/1.1" 200 305
INFO 2024-05-17 18:15:03,058 basehttp 39198 140335595386432 "GET /api/goods?page=2 HTTP/1.1" 301 0
WARNING 2024-05-17 18:15:03,080 log 39198 140335595386432 Not Found: /api/goods/
WARNING 2024-05-17 18:15:03,081 basehttp 39198 140335595386432 "GET /api/goods/?page=2 HTTP/1.1" 404 28
INFO 2024-05-17 18:15:11,992 basehttp 39198 140335595386432 "GET /api/goods?page_size=1 HTTP/1.1" 301 0
INFO 2024-05-17 18:15:12,030 basehttp 39198 140335595386432 "GET /api/goods/?page_size=1 HTTP/1.1" 200 305
INFO 2024-05-17 18:23:27,677 basehttp 39198 140335595386432 "POST /api/goods/ HTTP/1.1" 201 252
INFO 2024-05-17 18:23:30,677 basehttp 39198 140335595386432 "GET /api/goods?page_size=1 HTTP/1.1" 301 0
INFO 2024-05-17 18:23:30,710 basehttp 39198 140335595386432 "GET /api/goods/?page_size=1 HTTP/1.1" 200 354
INFO 2024-05-17 18:23:42,864 basehttp 39198 140335595386432 "GET /api/goods HTTP/1.1" 301 0
INFO 2024-05-17 18:23:42,902 basehttp 39198 140335595386432 "GET /api/goods/ HTTP/1.1" 200 558
